CREATE TABLE CITY
(ID NUMBER(11) PRIMARY KEY,
NAME VARCHAR(50) NOT NULL
);

CREATE TABLE REFREE
(ID NUMBER(11) PRIMARY KEY,
NAME VARCHAR(50) NOT NULL
);

CREATE TABLE INNINGS
(ID NUMBER(11) PRIMARY KEY,
INNINGS_NUMBER NUMBER(11) NOT NULL
);

CREATE TABLE EXTRA_TYPE
(
ID NUMBER(11) PRIMARY KEY,
NAME VARCHAR(50) NOT NULL
);

CREATE TABLE SKILL
(ID NUMBER(11) PRIMARY KEY,
NAME VARCHAR(50)
);

CREATE TABLE TEAM
(ID NUMBER(11) PRIMARY KEY,
NAME VARCHAR(50) NOT NULL,
COACH VARCHAR(50) NOT NULL,
HOME_CITY NUMBER(11) NOT NULL,
CAPTIAN NUMBER(11)
);

CREATE TABLE PLAYER
(ID NUMBER(11) PRIMARY KEY,
NAME VARCHAR(50),
COUNTRY VARCHAR(50),
SKILL_ID NUMBER(11),
TEAM_ID NUMBER(11)
);

CREATE TABLE VENUE
(ID NUMBER(11) PRIMARY KEY,
STADIUM_NAME VARCHAR(50) NOT NULL,
CITY_ID NUMBER(11)
);

CREATE TABLE EVENT
(ID NUMBER(11) PRIMARY KEY,
INNINGS_ID NUMBER(11),
EVENT_NO NUMBER(11) NOT NULL,
RAIDER_ID NUMBER(11),
RAID_POINTS NUMBER(11) NOT NULL,
DEFENDING_POINTS NUMBER(11) NOT NULL,
CLOCK_IN_SECONDS NUMBER(11) NOT NULL,
TEAM_ONE_SCORE NUMBER(11) NOT NULL,
TEAM_TWO_SCORE NUMBER(11) NOT NULL
);

CREATE TABLE EXTRA_EVENT
(ID NUMBER(11) PRIMARY KEY,
EVENT_ID NUMBER(11),
EXTRA_TYPE_ID NUMBER(11),
POINTS NUMBER(11) NOT NULL,
SCORING_TEAM_ID NUMBER(11)
);

CREATE TABLE OUTCOME
(ID NUMBER(11) PRIMARY KEY,
STATUS VARCHAR(100) NOT NULL,
WINNER_TEAM_ID NUMBER(11),
SCORE NUMBER(11),
PLAYER_OF_THE_MATCH NUMBER(11)
);

CREATE TABLE GAME
(ID NUMBER(11) PRIMARY KEY,
GAME_DATE DATE NOT NULL,
TEAM_ID_1 NUMBER(11),
TEAM_ID_2 NUMBER(11),
VENUE_ID NUMBER(11),
OUTCOME_ID NUMBER(11),
REFREE_ID_1 NUMBER(11),
REFREE_ID_2 NUMBER(11),
FIRST_INNINGS_ID NUMBER(11),
SECOND_INNINGS_ID NUMBER(11)
);

DROP TABLE CITY;

DROP TABLE INNINGS;

DROP TABLE SKILL;

DROP TABLE EXTRA_TYPE;